import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#02281F',
      paddingTop: 100,
    },
    title: {
      justifyContent: 'center',
      alignItems: 'center',
      position: 'absolute',
      top: 60,
    },
    titleContainer: {
      backgroundColor: '#7E57C2',
      width: 150,
      height: 40,
      justifyContent: 'center',
      alignItems: 'center',
      transform: [{ rotate: '-5deg' }],
    },
    title1: {
      fontSize: 26,
      fontWeight: 'bold',
      color: '#fff',
      transform: [{ rotate: '5deg' }],
    },
    title2: {
      fontSize: 26,
      fontWeight: 'bold',
      color: '#FFC107',
    },
    score: {
      fontSize: 24,
      fontWeight: 'bold',
      alignItems: 'center',
      justifyContent: 'center',
      margin: 50,
      color: '#fff',
    },
    selections: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    button: {
      width: 100,
      height: 100,
      borderRadius: 5,
      marginBottom: 30,
      justifyContent: 'center',
      alignItems: 'center',
      marginHorizontal: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.5,
      shadowRadius: 4,
      elevation: 6,
    },
    enemybutton: {
      width: 100,
      height: 100,
      borderRadius: 5,
      justifyContent: 'center',
      alignItems: 'center',
      marginHorizontal: 10,
      opacity: 0.7,
    },
    buttonImage: {
      width: 80,
      height: 80,
    },
    enemySelection: {
      fontSize: 18,
      marginBottom: 20,
      color: '#fff',
      marginTop: 20,
    },
    gameWinner: {
      fontSize: 24,
      fontWeight: 'bold',
      marginBottom: 60,
    },
    resetButton: {
      backgroundColor: '#7E57C2',
      borderRadius: 5,
      height: 40,
      justifyContent: 'center',
      alignItems: 'center',
      margin: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.5,
      shadowRadius: 4,
      elevation: 6,
      paddingLeft: 40,
      paddingRight: 40,
      borderWidth: 2,
      borderColor: '#FFC107',
    },
    resetButtonText: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#fff',
    },
    disabledButton: {
      opacity: 0.7,
    },
    highlightedButton: {
      borderWidth: 2,
      borderColor: '#FFC107',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.5,
      shadowRadius: 4,
      elevation: 6,
      borderRadius: 5,
    },
  });

  export default styles;